stages:
  - package
  - test

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml

package-firefox:
  image: alpine:latest
  stage: package
  script:
    - apt-get install zip
    - cd firefox ; zip -rFS ../jira-dark-mode.zip . * -x '*.git*' -x '*.DS_Store' ; cd ..
